name: postgres-zhparser builder

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - 'postgres-zhparser/**'

env:
  IMAGE_NAME: postgres-zhparser-alpine

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_DOCKER_USERNAME }}
          password: ${{ secrets.HUB_DOCKER_PASSWORD }}

      - name: Get version
        working-directory: postgres-zhparser
        run: echo "VERSION=$(awk -F " " '/ENV VERSION/ { print $3 }' Dockerfile)" >> $GITHUB_ENV

      - name: Build and push the image
        working-directory: postgres-zhparser
        run: |
          docker buildx build \
            --output=type=image,push=${{ github.ref == 'refs/heads/master' && 'true' || 'false' }} \
            --tag byzanteam/$IMAGE_NAME:latest \
            --tag byzanteam/$IMAGE_NAME:$VERSION \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
