name: postgres-zhparser builder

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - 'postgres-zhparser/**'

env:
  IMAGE_NAME: postgres-zhparser-alpine

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: postgres-zhparser
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        if: github.ref== 'refs/heads/master'
        run: echo "${{ secrets.HUB_DOCKER_PASSWORD }}" | docker login -u ${{ secrets.HUB_DOCKER_USERNAME }} --password-stdin

      - name: Push image
        if: github.ref== 'refs/heads/master'
        working-directory: postgres-zhparser
        run: |
          IMAGE_ID=byzanteam/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # get version from VERSION file
          VERSION=$(awk -F " " '/ENV VERSION/ { print $3 }' Dockerfile)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
